### ISSUE TITLE
help on quick box

### ISSUE THREAD

**Issue by mohsin2928** [ScRiPt1337/hackthebox_notes#1]
still the same error message 

File "quick_auto_pwn.py", line 254, in getroot
    if not s.login('10.10.10.186', 'root', root, sync_multiplier=5, auto_prompt_reset=False):
  File "/usr/lib/python2.7/dist-packages/pexpect/pxssh.py", line 402, in login
    raise ExceptionPxssh('password refused')
pexpect.pxssh.ExceptionPxssh: password refused

**Comment by ScRiPt1337** [comment]
bro i already fixed it clone the repo again
